baseURL: http://something-fresh.org/
languageCode: en-us
title: Hugo Fresh Theme

module:
  # uncomment line below for local development of module
  #workspace: hugo.work
  imports:
  - path: github.com/cpretus-dev/hugo-fresh.git
  - path: github.com/jgthms/bulma
    mounts:
    - source: bulma.sass
      target: assets/bulma/bulma.sass
    - source: bulma-rtl.sass
      target: assets/bulma/bulma-rtl.sass
    - source: sass
      target: assets/bulma/sass
    - source: sass/base
      target: assets/bulma/sass/base
    - source: sass/components
      target: assets/bulma/sass/components
    - source: sass/elements
      target: assets/bulma/sass/elements
    - source: sass/form
      target: assets/bulma/sass/form
    - source: sass/grid
      target: assets/bulma/sass/grid
    - source: sass/helpers
      target: assets/bulma/sass/helpers
    - source: sass/layout
      target: assets/bulma/sass/layout
    - source: sass/utilities
      target: assets/bulma/sass/utilities

googleAnalytics: # Put in your tracking code without quotes like this: UA-XXX for universal tracking or G-XXX analytics v4 tracking
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy
  description:
  # Preloader ensures images are loaded before displaying to the user. If you don't want it uncomment to set it to false
  # preloader: false
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/lablogo6.png
    link: /
    # Default width/height. Uncomment if you need to change
    # width: 112
    # height: 28
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Social Brain Lab Barcelona
    # Hero subtitle (optional)
    subtitle: "Director: Clara Pretus, Ph.D."
    # Button text
    buttontext: We are recruiting!
    # Where the main hero button links to
    buttonlink: "/blog/joinus"
    # Hero image (from static/images/___)
    image: illustrations/twobrains.png
    # Footer logos (from static/images/logos/clients/*.svg)
    # urls are optional
    clientlogos:
    - logo: lablogo6-black
      url: https://www.socialbrainlab.com
    - logo: uab
      url: https://www.uab.cat/web/universitat-autonoma-de-barcelona-1345467954774.html
    - logo: hospitalmar
      url: https://www.imim.es/
    - logo: twitter
      url: https://twitter.com/ClaraPretus 
    - logo: osf
      url: https://osf.io/4b3rt
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Home
    url: /
  - title: Team
    url: /blog/team
  - title: Research
    sublinks:
    - title: Moral psychology of AI
      url: /projects/valawai
    - title: Misinformation
      url: /projects/bial
    - title: Extremism
      url: /projects/arenas
  - title: Publications
    url: /blog/publications
  - title: News
    url: /blog/news
  - title: Join Us
    url: /blog/joinus
  - title: Contact Us
    url: /
    button: true
  # sidebar:
  #   # Logo (from /images/logos/___.svg)
  #   logo: fresh-square
  #   sections:
  #   - title: User
  #     icon: user
  #     links:
  #     - text: Profile
  #       url: /
  #     - text: Account
  #       url: /
  #     - text: Settings
  #       url: /
  #   - title: Messages
  #     icon: envelope
  #     links:
  #     - text: Inbox
  #       url: /
  #     - text: Compose
  #       url: /
  #   - title: Images
  #     icon: image
  #     links:
  #     - text: Library
  #       url: /
  #     - text: Upload
  #       url: /
  #   - title: Settings
  #     icon: cog
  #     links:
  #     - text: User settings
  #       url: /
  #     - text: App settings
  #       url: /
  section0:
    title: Welcome to our lab!

  section1:
    title: Research
  #  subtitle: with great responsibility
    tiles:
    - title: Morality and AI
      icon: ai
      text: Can AI help us make better moral judgments?
      url: /projects/valawai
      buttonText: Read more
    - title: Misinformation
      icon: misinformation
      text: Is cognitive rigidity linked to fake news consumption?
      url: /projects/bial
      buttonText: Read more
    - title: Extremism
      icon: politics
      text: Can changes in social media diet decrease extremism? 
      url: /projects/arenas
      buttonText: Read more
  section2:
    title: Featured publications
    #subtitle: And we know it
    features:
    - title: The Role of Political Devotion in Sharing Partisan Misinformation and Resistance to Fact-checking.
      text: <br> In a set of studies across the U.S. and Spain, we found that far-right partisans were more likely to share misinformation relevant to conservative sacred values and were resistant to fact-checks and accuracy nudges. At a brain level, we observed a strong response in brain regions implicated in norm compliance and mentalizing to misinformation that included sacred values (vs. nonsacred values) among far-right partisans. This work provides new theoretical and practical insights into misinformation sharing and resistance to fact-checking among far-right partisans. <br><br>[Read more](https://psycnet.apa.org/fulltext/2023-83147-001.html)
    - title: "The Misleading Count: An Identity-Based Intervention to Mitigate the Spread of Partisan Misinformation."
      text: <br> Across three experiments in the U.S. and UK, we found that crowdsourcing accuracy judgments by adding a Misleading count next to the Like count reduced participants’ reported likelihood to share inaccurate information about partisan issues by 25% compared to a control condition. The Misleading count was also more effective when it reflected in-group norms (from fellow Democrats/Republicans) compared to the norms of general users, though this effect was absent in a less politically polarized context (UK).<br><br>[Read more](https://psyarxiv.com/7j26y/)
    - title: "The Psychology of Hate: Moral Concerns Differentiate Hate from Dislike"
      text: <br> We investigated whether any differences in the psychological conceptualization of hate and dislike were simply a matter of degree of negativity (i.e., hate falls on the end of the continuum of dislike) or also morality (i.e., hate is imbued with distinct moral components that distinguish it from dislike). In three lab studies in Canada and the U.S., we found that hated attitude objects were more negative than disliked attitude objects and associated with moral beliefs and emotions, even after adjusting for differences in negativity. <br><br>[Read more](https://onlinelibrary.wiley.com/doi/10.1002/ejsp.2906)
      #icon: 
  section3:
    #title: Our team
    #subtitle: To rule them all
    image: illustrations/team.png
    buttonText: Meet the team
    buttonLink: /blog/team
  section4:
    title: Supported by
    image:
      - images: erclogo
      - images: eiclogo
      - images: biallogo
      - images: artilogo
    #subtitle: Lorem ipsum sit dolor amet is a dummy text used by typography industry
    # clients:
    # - name: Irma Walters
    #   quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
    #   job: Accountant
    #   img: 1
    # - name: John Bradley
    #   quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
    #   job: Financial Analyst
    #   img: 2
    # - name: Gary Blackman
    #   quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
    #   job: HR Manager
    #   img: 3
  section5:
    title: Contact us
    #subtitle: We'd love to hear from you
    buttonText: Send Message
    # action: https://formspree.io/f/<form_id>
    # method: POST
  footer:
    # Logo (from /images/logos/___)
    logo: lablogo6-white.svg
    # Social Media Title
    socialmediatitle: Follow Us
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://twitter.com/ClaraPretus
      icon: twitter
    - link: https://github.com/cpretus-dev
      # Icons are from Font Awesome
      icon: github
    # - link: https://dribbble.com/#
    #   icon: dribbble
    # - link: https://facebook.com/#
    #   icon: facebook
    # - link: https://bitbucket.org/#
    #   icon: bitbucket
    bulmalogo: true
    quicklinks:
      column1:
        title: "Address"
        links:
        - text: Parc de Recerca Biomèdica
          link: /https://www.prbb.org/
        - text: c/ Doctor Aiguader, 88
          link: /
        - text: 08003 Barcelona 
          link: /
      column2:
        title: "Credit"
        links:
        - text: Icons by Freepik
          link: https://www.flaticon.com/
        - text: Logo made with Canva
          link: https://www.canva.com/  
        - text: Illustration made with getimg.ai
          link: https://getimg.ai/
      # column3:
      #   title: "Blog"
      #   links:
      #   - text: Latest news
      #     link: /blog/first
      #   - text: Tech articles
      #     link: /blog/second
